version: 0.2

env:
  variables:
    CLUSTER_NAME: auth-service-cluster
    REGION: us-west-2
    DEPLOYMENT_NAME: auth-service
    CONTAINER_NAME: auth-service
    REPOSITORY_URI: 329599621234.dkr.ecr.us-west-2.amazonaws.com/auth-service-repo

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install --upgrade awscli
      - echo Granting execute permission to Gradle wrapper...
      - chmod +x ./gradlew

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo Building the Spring Boot application...
      - ./gradlew build
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION

  post_build:
    commands:
      - echo Pushing the Docker images to ECR...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION

      - echo Updating kubeconfig for cluster $CLUSTER_NAME...
      - export AWS_SDK_LOAD_CONFIG=1
      - aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME

      - echo Deploying new image to EKS...
      - kubectl set image deployment/$DEPLOYMENT_NAME $CONTAINER_NAME=$REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - kubectl rollout status deployment/$DEPLOYMENT_NAME

artifacts:
  files:
    - deployment.yaml
